Fix: Fixed endpoints needed for making a reservation
76eren/IPSEN5-backend pull request #25
Opened 2024-06-03 09:11 UTC by Yaman-Kwefati

2024-06-04 12:09 UTC, s1143282 requested changes

2024-06-04 12:09 UTC, s1143282 commented on src/main/java/com/cgi/ipsen5/Controller/FloorController.java
> +    @GetMapping(value = "/building/{buildingId}")
ik zou de pathvariable buildingId gewoon naar id veranderen

2024-06-04 12:09 UTC, s1143282 commented on src/main/java/com/cgi/ipsen5/Controller/WingController.java
> +    @GetMapping(value = "/floor/{floorId}")
hier ook veranderen naar id graag

2024-06-05 07:11 UTC, s1143282 approved these changes

2024-06-05 08:58 UTC, isabelhb approved these changes

2024-06-05 08:58 UTC, merged