Feat/delete locations: can delete location with soft delete and added validation
76eren/IPSEN5-backend pull request #34
Opened 2024-06-07 18:32 UTC by s1143282

2024-06-10 13:09 UTC, Yaman-Kwefati requested changes
1 klein dingetje aanpassen en het is goed

2024-06-10 13:09 UTC, Yaman-Kwefati commented on src/main/java/com/cgi/ipsen5/Service/LocationService.java
> +        Location location = this.getLocationById(id);
je kunt hier beter de existsById gebruiken want die kan de exception regelen

2024-06-12 16:49 UTC, Yaman-Kwefati approved these changes

2024-06-13 08:33 UTC, StanSmits approved these changes

2024-06-13 08:33 UTC, merged