FIX: Fixed small error of getting data about available rooms
76eren/IPSEN5-backend pull request #35
Opened 2024-06-09 19:08 UTC by Yaman-Kwefati

2024-06-10 18:15 UTC, s1143282 approved these changes

2024-06-13 08:34 UTC, StanSmits requested changes
Kan je die requestparam niet via een duo sturen?

2024-06-13 08:48 UTC, Yaman-Kwefati commented
> Kan je die requestparam niet via een duo sturen?

nee, omdat het een get request is

2024-06-13 09:52 UTC, StanSmits approved these changes

2024-06-13 09:52 UTC, merged