Fix: Fixed getting available rooms.
76eren/IPSEN5-backend pull request #39
Opened 2024-06-14 13:55 UTC by Yaman-Kwefati

Fixed getting available rooms where there was a bug that listed meeting rooms even when it was reserved and fixed wrong building listing of location.

2024-06-15 11:30 UTC, s1143282 approved these changes

2024-06-16 10:06 UTC, isabelhb requested changes

2024-06-16 10:06 UTC, isabelhb commented on src/main/java/com/cgi/ipsen5/Dao/ReservationDao.java
>          // TODO: check if user exists first
Deze todo moet nog gedaan worden

2024-06-17 12:59 UTC, Yaman-Kwefati commented on src/main/java/com/cgi/ipsen5/Dao/ReservationDao.java
>          // TODO: check if user exists first
dit is van eren

2024-06-17 13:04 UTC, isabelhb approved these changes

2024-06-17 13:04 UTC, merged